=== EX22/EpamTraining/Task04/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://training.by/flowers"
        xmlns:tns="http://training.by/flowers"
        elementFormDefault="qualified">

    <element name="flowers">
        <complexType>
            <sequence>
                <element name="flower"
                         type="tns:Flowers"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Flowers">
        <all>
            <element name="name" type="string"/>
            <element name="soil" type="tns:Soil"/>
            <element name="origin" type="tns:Origin"/>
            <element name="visual-parameters" type="tns:Visual-parameters"/>
            <element name="growing-tips" type="tns:Growing-tips"/>
            <element name="multiplying" type="tns:Multiplying"/>
            <element name="planting-date" type="date"/>
        </all>
    </complexType>

    <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="loam"/>
            <enumeration value="sandy"/>
            <enumeration value="silt"/>
            <enumeration value="mixed"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <!-- Add all country's enum here-->
            <enumeration value="Africa"/>
            <enumeration value="Australia"/>
            <enumeration value="Asia"/>
            <enumeration value="China"/>
            <enumeration value="Europe"/>
            <enumeration value="North-America"/>
            <enumeration value="South-America"/>
        </restriction>
    </simpleType>

    <complexType name="Visual-parameters">
        <sequence>
            <element name="size" type="tns:Size"/>
            <element name="leaf-color" type="string"/>
            <element name="stem-color" type="string" default="green"/>
        </sequence>
    </complexType>

    <complexType name="sizeRestriction">
        <simpleContent>
            <restriction base="positiveInteger">
                <maxInclusive value="3000"/>
            </restriction>
        </simpleContent>
    </complexType>

    <complexType name="Size">
        <simpleContent>
            <extension base="tns:sizeRestriction">
                <attribute name="type" type="string"/>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="Growing-tips">
        <sequence>
            <element name="temperature" type="tns:Temperature"/>
            <element name="humidity" type="positiveInteger"/>
            <element name="light-level" type="tns:Light-level"/>
            <element name="water" type="tns:Water"/>
        </sequence>
    </complexType>

    <complexType name="temperatureRestriction">
        <simpleContent>
            <restriction base="positiveInteger">
                <maxInclusive value="50"/>
            </restriction>
        </simpleContent>
    </complexType>

    <complexType name="Temperature">
        <simpleContent>
            <extension base="tns:temperatureRestriction">
                <attribute name="type" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <complexType name="waterRestriction">
        <simpleContent>
            <restriction base="positiveInteger">
                <maxInclusive value="2000"/>
            </restriction>
        </simpleContent>
    </complexType>

    <complexType name="Water">
        <simpleContent>
            <extension base="tns:waterRestriction">
                <attribute name="type" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

    <simpleType name="Light-level">
        <restriction base="string">
            <enumeration value="low"/>
            <enumeration value="medium"/>
            <enumeration value="high"/>
        </restriction>
    </simpleType>

    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="seeds"/>
            <enumeration value="stems"/>
            <enumeration value="roots"/>
        </restriction>
    </simpleType>

</schema>

=== EX22/EpamTraining/Task04/data/flowersTest.xml
<?xml version="1.0" encoding="UTF-8" ?>

<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://training.by/flowers"
         xsi:schemaLocation="http://training.by/flowers  /resources/flowers.xsd">
    <flower>

        <name>African-Violets</name>

        <soil>mixed</soil>

        <origin>Africa</origin>

        <visual-parameters>
            <size type="cm">20</size>
            <leaf-color>blue</leaf-color>
            <stem-color>green</stem-color>
        </visual-parameters>

        <growing-tips>
            <temperature type="celsius">18</temperature>
            <humidity>30</humidity>
            <light-level>medium</light-level>
            <water type="ml/week">150</water>
        </growing-tips>

        <multiplying>stems</multiplying>
        <planting-date>2019-03-31</planting-date>
    </flower>

    <flower>

        <name>Amazon-Lilies</name>

        <soil>silt</soil>

        <origin>North-America</origin>

        <visual-parameters>
            <size type="cm">25</size>
            <leaf-color>white</leaf-color>
            <stem-color>green</stem-color>
        </visual-parameters>

        <growing-tips>
            <temperature type="celsius">18</temperature>
            <humidity>30</humidity>
            <light-level>high</light-level>
            <water type="ml/week">100</water>
        </growing-tips>

        <multiplying>roots</multiplying>
        <planting-date>2019-03-20</planting-date>
    </flower>

    <flower>

        <name>Chinese-Hibiscus</name>

        <soil>sandy</soil>

        <origin>Asia</origin>

        <visual-parameters>
            <size type="cm">20</size>
            <leaf-color>yellow</leaf-color>
            <stem-color>green</stem-color>
        </visual-parameters>

        <growing-tips>
            <temperature type="celsius">20</temperature>
            <humidity>60</humidity>
            <light-level>high</light-level>
            <water type="ml/week">400</water>
        </growing-tips>

        <multiplying>roots</multiplying>
        <planting-date>2019-04-04</planting-date>
    </flower>

</flowers>
